services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: img_to_text_app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
